#!/usr/bin/env bash
# installs nginx and starts a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp/var/www/html/index.nginx.debian.html /var/www/html/index/debian.html.bckp

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

service nginx restart
