#!/usr/bin/env bash
# installs nginx and starts a remote server

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# Check if the file exists before copying
if [ -f "/var/www/html/index.nginx.debian.html" ]; then
    cp /var/www/html/index.nginx.debian.html /var/www/html/index/debian.html.bckp
else
    echo "Error: index.nginx.debian.html not found. Creating a new file."
fi

# Create a new index file with "Hello World!"
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Restart nginx service
service nginx restart
