#!/usr/bin/env bash
# redirection


apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

REDIRECT_CONFIG="location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

sed -i "/server_name _;/a $REDIRECT_CONFIG" /etc/nginx/sites-available/default

service restart nginx
