#!/usr/bin/env bash
# installs HAproxy so that it sends traffic to web 01 and web 02

apt-get install -y software-properties-common
add-apt repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.0 \*

echo "ENABLED=1" > /etc/default/haproxy
